import { v4 as uuid } from "uuid";

export const accountUnusedFields = [
    {
      fieldId: 1,
      fieldName: "Account Name",
      isUsed: false,
      schema: {
        unusedField: 1,
        label: "Account Name",
        name: "accountName",
        placeholder: "Enter Account Name",
        required: "true",
        requiredErrorMessage: "Please enter account name",
        pattern: "",
        patternValidationErrorMessage: "",
        minLength: "",
        minLengthErrorMessage: "",
        maxLength: "",
        maxLengthErrorMessage: "",
        emailValidation: "",
        emailValidationErrorMessage: "",
        maxValue: "",
        maxValueErrorMessage: "",
        minValue: "",
        minValueErrorMessage: "",
        fileTypeValidation: "",
        fileTypeValidationErrorMessage: "",
        fileSizeValidation: "",
        fileSizeValidationErrorMessage: "",
        options: "",
        parent: "",
        type: "text",
        fieldId: uuid(),
      },
    },
    {
      fieldId: 2,
      fieldName: "Sales Name",
      isUsed: false,
      schema: {
        unusedField: 2,
        label: "Sales Name",
        name: "salasName",
        placeholder: "Enter Sales Name",
        required: "true",
        requiredErrorMessage: "Please enter sales name",
        pattern: "",
        patternValidationErrorMessage: "",
        minLength: "",
        minLengthErrorMessage: "",
        maxLength: "",
        maxLengthErrorMessage: "",
        emailValidation: "",
        emailValidationErrorMessage: "",
        maxValue: "",
        maxValueErrorMessage: "",
        minValue: "",
        minValueErrorMessage: "",
        fileTypeValidation: "",
        fileTypeValidationErrorMessage: "",
        fileSizeValidation: "",
        fileSizeValidationErrorMessage: "",
        options: "",
        parent: "",
        type: "text",
        fieldId: uuid(),
      },
    },
  ];