import { v4 as uuid } from "uuid";

export const accountUnusedFields = [
  {
    "label": "Account Name",
    "name": "accountName",
    "placeholder": "Enter account name",
    "required": "true",
    "requiredErrorMessage": "Account name is required",
    "pattern": "",
    "patternValidationErrorMessage": "",
    "minLength": "",
    "minLengthErrorMessage": "",
    "maxLength": "",
    "maxLengthErrorMessage": "",
    "emailValidation": "",
    "emailValidationErrorMessage": "",
    "maxValue": "",
    "maxValueErrorMessage": "",
    "minValue": "",
    "minValueErrorMessage": "",
    "fileTypeValidation": "",
    "fileTypeValidationErrorMessage": "",
    "fileSizeValidation": "",
    "fileSizeValidationErrorMessage": "",
    "options": "",
    "parent": "",
    "visible": "[]",
    "userGroup": [],
    "tableConfig": "",
    "tableEdit": "",
    "tableDelete": "",
    "tableAPI": "",
    "tableAPIURL": "",
    "countryOptions": {
      "countryField": "",
      "countryList": []
    },
    "type": "text",
    "fieldId": "70ce8ae7-e34e-4d07-ab04-09c62f6e586f"
  },
  {
    "label": "Sales Name",
    "name": "salesName",
    "placeholder": "Enter Sales Name",
    "required": "true",
    "requiredErrorMessage": "Sales name is required",
    "pattern": "",
    "patternValidationErrorMessage": "",
    "minLength": "",
    "minLengthErrorMessage": "",
    "maxLength": "",
    "maxLengthErrorMessage": "",
    "emailValidation": "",
    "emailValidationErrorMessage": "",
    "maxValue": "",
    "maxValueErrorMessage": "",
    "minValue": "",
    "minValueErrorMessage": "",
    "fileTypeValidation": "",
    "fileTypeValidationErrorMessage": "",
    "fileSizeValidation": "",
    "fileSizeValidationErrorMessage": "",
    "options": "",
    "parent": "",
    "visible": "[]",
    "userGroup": [],
    "tableConfig": "",
    "tableEdit": "",
    "tableDelete": "",
    "tableAPI": "",
    "tableAPIURL": "",
    "countryOptions": {
      "countryField": "",
      "countryList": []
    },
    "type": "text",
    "fieldId": "60942bce-f7e8-4b80-a623-6333f3142027"
  }
];
