export const FETCH_USERGROUP = "FETCH_USERGROUP";
export const FETCH_USERGROUP_SUCCESS = "FETCH_USERGROUP_SUCCESS";
export const FETCH_USERGROUP_FAILURE = "FETCH_USERGROUP_FAILURE";

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
