export const FETCH_JOB = "FETCH_JOB";
export const FETCH_JOB_SUCCESS = "FETCH_JOB_SUCCESS";
export const FETCH_JOB_FAILURE = "FETCH_JOB_FAILURE";

export const FETCH_JOBS = "FETCH_JOBS";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_FAILURE = "FETCH_JOBS_FAILURE";

export const CREATE_JOB = "CREATE_JOB";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_FAILURE = "CREATE_JOB_FAILURE";

export const CREATE_JOB_DOCUMENTS = "CREATE_JOB_DOCUMENTS";
export const CREATE_JOB_DOCUMENTS_SUCCESS = "CREATE_JOB_DOCUMENTS_SUCCESS";
export const CREATE_JOB_DOCUMENTS_FAILURE = "CREATE_JOB_DOCUMENTS_FAILURE";

export const CLEAR_JOB = "CLEAR_JOB";

export const FETCH_JOB_DATA = "FETCH_JOB_DATA";
export const FETCH_JOB_DATA_SUCCESS = "FETCH_JOB_DATA_SUCCESS";
export const FETCH_JOB_DATA_FAILURE = "FETCH_JOB_DATA_FAILURE";

export const FETCH_JOBS_FIELDS_ALL = "FETCH_JOBS_FIELDS_ALL";
export const FETCH_JOBS_FIELDS_ALL_SUCCESS = "FETCH_JOBS_FIELDS_ALL_SUCCESS";
export const FETCH_JOBS_FIELDS_ALL_FAILURE = "FETCH_JOBS_FIELDS_ALL_FAILURE";

