export const FETCH_JOB_FORM = "FETCH_JOB_FORM";
export const FETCH_JOB_FORM_SUCCESS = "FETCH_JOB_FORM_SUCCESS";
export const FETCH_JOB_FORM_FAILURE = "FETCH_JOB_FORM_FAILURE";

export const FETCH_JOB_FORM_SUBMISSION = "FETCH_JOB_FORM_SUBMISSION";
export const FETCH_JOB_FORM_SUBMISSION_SUCCESS =
  "FETCH_JOB_FORM_SUBMISSION_SUCCESS";
export const FETCH_JOB_FORM_SUBMISSION_FAILURE =
  "FETCH_JOB_FORM_SUBMISSION_FAILURE";

export const CLEAR_JOB_FORM_SUBMISSION = "CLEAR_JOB_FORM_SUBMISSION";

export const SET_FORM_SUBMISSION = "SET_FORM_SUBMISSION";
