// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_REVENUE_CHARTS_DATA = "GET_REVENUE_CHARTS_DATA";

export const FETCH_JOB_COUNTS = "FETCH_JOB_COUNTS";
export const FETCH_JOB_COUNTS_SUCCESS = "FETCH_JOB_COUNTS_SUCCESS";
export const FETCH_JOB_COUNTS_FAILURE = "FETCH_JOB_COUNTS_FAILURE";
