export const FETCH_ACCOUNTNAMES = 'FETCH_ACCOUNTNAMES';
export const FETCH_ACCOUNTNAMES_SUCCESS = 'FETCH_ACCOUNTNAMES_SUCCESS';
export const FETCH_ACCOUNTNAMES_FAILURE = 'FETCH_ACCOUNTNAMES_FAILURE';
