export const FETCH_PARENTCOMPANY = 'FETCH_PARENTCOMPANY';
export const FETCH_PARENTCOMPANY_SUCCESS = 'FETCH_PARENTCOMPANY_SUCCESS';
export const FETCH_PARENTCOMPANY_FAILURE = 'FETCH_PARENTCOMPANY_FAILURE';

