export const EDIT_PROFILE = "EDIT_PROFILE";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const RESET_PROFILE_FLAG = "RESET_PROFILE_FLAG";

export const PROFILE_PERMISSION_SUCCESS = "PROFILE_PERMISSION_SUCCESS";
export const PROFILE_PERMISSION_ERROR = "PROFILE_PERMISSION_ERROR";
export const RESET_PROFILE_PERMISSION = "RESET_PROFILE_PERMISSION_FLAG";
