export const EDIT_PROFILE = "EDIT_PROFILE";
export const FETCH_PROFILE = "FETCH_PROFILE";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const DELETE_PROFILE = "DELETE_PROFILE";

export const RESET_PROFILE_FLAG = "RESET_PROFILE_FLAG";

