import * as yup from "yup";

export const initialValues = {
    // Required Fields
    accName                         : "",
    accContact                      : "",
    jobTitle                        : "",
    dateOpen                        : "",
    jobType                         : "",
    primarySkills                   : "",
    secondarySkills                 : "",
    noHeadcount                     : "",
    workType                        : "",
    jobDesc                         : "",
    visaStatus                      : "",
    country                         : "",
    turnaroundTimeInput             : "",
    turnaroundTimeDays              : "",
    salaryBudgetLocalInput          : "",
    salaryBudgetLocalRange          : "",
    budgetType                      : "",
    jobDocs                         : "",

    // Non-required Values 
    salesManager                    : "",
    targetClosingDate               : "",
    clientJobId                     : "",
    duration                        : "",
    languages                       : "",
    reqDocs                         : "",
    workLoc                         : "",
    priority                        : "",
    qualification                   : "",
    jobRatingSales                  : "",
    securityClearance               : "",
    localCurrency                   : "",
    salaryBudgetSGD                 : "",
    expectedMarginMinInput          : "",
    expectedMarginMinCurrency       : "",
    expectedMarginMaxInput          : "",
    expectedMarginMaxCurrency       : "",
    expectedMarginSGD               : "",
    technicalScreening              : "",
    technicalScreeningTemp          : "",
    recruitmentScreeningTemp        : "",
    jobRemarks                      : "",
}

export const schema = yup.object().shape({
    accName                         : yup.string().required("Please select an account name."),
    accContact                      : yup.string().required("Please enter an account contact."),
    jobTitle                        : yup.string().required("Please enter a job title."),
    dateOpen                        : yup.date().required("Please select an opening date."),
    jobType                         : yup.string().required("Please select a job type."),
    primarySkills                   : yup.string().required("Please select a primary skill."),
    secondarySkills                 : yup.string().required("Please select a secondary skill."),
    noHeadcount                     : yup.string().required("Please select a headcount."),
    workType                        : yup.string().required("Please select a work type."),
    jobDesc                         : yup.string().required("Please enter a job description."),
    visaStatus                      : yup.string().required("Please select a visa status."),
    country                         : yup.string().required("Please select a country."),
    turnaroundTimeInput             : yup.string().required("Please enter a turnaround time."),
    turnaroundTimeDays              : yup.string().required("Please select the no. of days."),
    salaryBudgetLocalInput          : yup.string().required("Please enter the salary budget input."),
    salaryBudgetLocalRange          : yup.string().required("Please select a range."),
    budgetType                      : yup.string().required("Please select a budget type."),
    jobDocs                         : yup.string().required("Please upload a job document."),

    salesManager                    : yup.string().notRequired().nullable(),
    targetClosingDate               : yup.date().notRequired().nullable(),
    clientJobId                     : yup.string().notRequired().nullable(),
    duration                        : yup.string().notRequired().nullable(),
    languages                       : yup.string().notRequired().nullable(),
    reqDocs                         : yup.string().notRequired().nullable(),
    workLoc                         : yup.string().notRequired().nullable(),
    priority                        : yup.string().notRequired().nullable(),
    qualification                   : yup.string().notRequired().nullable(),
    jobRatingSales                  : yup.string().notRequired().nullable(),
    securityClearance               : yup.string().notRequired().nullable(),
    localCurrency                   : yup.string().notRequired().nullable(),
    salaryBudgetSGD                 : yup.string().notRequired().nullable(),
    expectedMarginMinInput          : yup.string().notRequired().nullable(),
    expectedMarginMinCurrency       : yup.string().notRequired().nullable(),
    expectedMarginMaxInput          : yup.string().notRequired().nullable(),
    expectedMarginMaxCurrency       : yup.string().notRequired().nullable(),
    expectedMarginSGD               : yup.string().notRequired().nullable(),
    technicalScreening              : yup.string().notRequired().nullable(),
    technicalScreeningTemp          : yup.string().notRequired().nullable(),
    recruitmentScreeningTemp        : yup.string().notRequired().nullable(),
    jobRemarks                      : yup.string().notRequired().nullable(),
})