const primarySkills = [
    'Communication',
    'Problem Solving',
    'Teamwork',
    'Time Management',
    'Adaptability',
    'Creativity',
    'Critical Thinking',
    'Leadership',
    'Organizational Skills',
    'Attention to Detail',
    'Analytical Skills',
    'Customer Service',
    'Project Management',
    'Negotiation',
    'Research',
    'Presentation Skills',
    'Technical Proficiency',
    'Conflict Resolution',
    'Multitasking',
    'Decision Making',
    'Networking',
    'Planning',
    'Innovation',
    'Emotional Intelligence',
    'Adaptability',
    'Self-Motivation',
    'Cultural Awareness',
    'Financial Literacy',
    'Marketing',
    'Sales',
    'Public Speaking',
    'Foreign Languages',
  ];

  const secondarySkills = [
    'Data Analysis',
    'UX/UI Design',
    'Content Writing',
    'Social Media Marketing',
    'Search Engine Optimization (SEO)',
    'Database Management',
    'Statistical Analysis',
    'Mobile App Development',
    'Graphic Design',
    'Video Editing',
    'Email Marketing',
    'Copywriting',
    'User Research',
    'Network Security',
    'Cloud Computing',
    'UI/UX Prototyping',
    'Agile Methodologies',
    'Data Visualization',
    'System Administration',
    'Quality Assurance (QA)',
    'DevOps',
    'Machine Learning',
    'Artificial Intelligence (AI)',
    'Blockchain Technology',
    'Cybersecurity',
    'Game Development',
    'Virtual Reality (VR) Development',
    'Augmented Reality (AR) Development',
    '3D Modeling',
    'Robotics',
    'Natural Language Processing (NLP)',
    'IoT (Internet of Things)',
    'Big Data Analytics',
    'Cybersecurity',
    'Business Intelligence (BI)',
  ];

  const jobTypes = [
    'Full-time',
    'Part-time',
    'Contract',
    'Freelance',
    'Temporary',
    'Internship',
    'Remote',
    'Entry-level',
    'Mid-level',
    'Senior-level',
    'Managerial',
    'Executive',
    'Consulting',
    'Volunteer',
    'Seasonal',
    'Apprenticeship',
    'Co-op',
  ];

  const jobDurations = [
    'Full-time',
    'Part-time',
    'Contract',
    'Temporary',
    'Freelance',
    'Internship',
    'Seasonal',
    'Project-based',
    'Consulting',
    'Volunteer',
    'Remote',
  ];
  

  export {
    primarySkills,
    secondarySkills,
    jobTypes,
    jobDurations
  }

