export const FETCH_ACCOUNT = "FETCH_ACCOUNT";
export const FETCH_ACCOUNT_SUCCESS = "FETCH_ACCOUNT_SUCCESS";
export const FETCH_ACCOUNT_FAILURE = "FETCH_ACCOUNT_FAILURE";

export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";
export const FETCH_ACCOUNTS_SUCCESS = "FETCH_ACCOUNTS_SUCCESS";
export const FETCH_ACCOUNTS_FAILURE = "FETCH_ACCOUNTS_FAILURE";

export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAILURE = "CREATE_ACCOUNT_FAILURE";

export const POST_ACCOUNT = "POST_ACCOUNT";
export const POST_ACCOUNT_SUCCESS = "POST_ACCOUNT_SUCCESS";
export const POST_ACCOUNT_FAILURE = "POST_ACCOUNT_FAILURE";

export const PUT_ACCOUNT = "PUT_ACCOUNT";
export const PUT_ACCOUNT_SUCCESS = "PUT_ACCOUNT_SUCCESS";
export const PUT_ACCOUNT_FAILURE = "PUT_ACCOUNT_FAILURE";
