// CREATE CUSTOM VIEW
export const CREATE_CUSTOM_VIEW = "CREATE_CUSTOM_VIEW";
export const CREATE_CUSTOM_VIEW_SUCCESS = "CREATE_CUSTOM_VIEW_SUCCESS";
export const CREATE_CUSTOM_VIEW_FAILURE = "CREATE_CUSTOM_VIEW_FAILURE";
