export const FORGET_PASSWORD = "FORGET_PASSWORD"
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS"
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR"

export const VALIDATE_RESET_TOKEN = "VALIDATE_RESET_TOKEN";
export const VALIDATE_RESET_TOKEN_SUCCESS = "VALIDATE_RESET_TOKEN_SUCCESS";
export const VALIDATE_RESET_TOKEN_ERROR = "VALIDATE_RESET_TOKEN_ERROR";

export const RESET_FORGET_PASSWORD_META = "RESET_FORGET_PASSWORD_META";

