export const FETCH_CITY = 'FETCH_CITY';
export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS';
export const FETCH_CITY_FAILURE = 'FETCH_CITY_FAILURE';

// export const FETCH_BILLINGCITY = 'FETCH_BILLINGCITY';
// export const FETCH_BILLINGCITY_SUCCESS = 'FETCH_BILLINGCITY_SUCCESS';
// export const FETCH_BILLINGCITY_FAILURE = 'FETCH_BILLINGCITY_FAILURE';
