export const FETCH_ACCOUNTCONTACTS = 'FETCH_ACCOUNTCONTACTS';
export const FETCH_ACCOUNTCONTACTS_SUCCESS = 'FETCH_ACCOUNTCONTACTS_SUCCESS';
export const FETCH_ACCOUNTCONTACTS_FAILURE = 'FETCH_ACCOUNTCONTACTS_FAILURE';
