export const FETCH_COUNTRYCURRENCY = 'FETCH_COUNTRYCURRENCY';
export const FETCH_COUNTRYCURRENCY_SUCCESS = 'FETCH_COUNTRYCURRENCY_SUCCESS';
export const FETCH_COUNTRYCURRENCY_FAILURE = 'FETCH_COUNTRYCURRENCY_FAILURE';
