export const TAG_JOB = "TAG_JOB";
export const TAG_JOB_SUCCESS = "TAG_JOB_SUCCESS";
export const TAG_JOB_FAILURE = "TAG_JOB_FAILURE";
export const TAG_JOB_RESET = "TAG_JOB_RESET";

export const TAG_JOB_ALL = "TAG_JOB_ALL";
export const TAG_JOB_ALL_SUCCESS = "TAG_JOB_ALL_SUCCESS";
export const TAG_JOB_ALL_FAILURE = "TAG_JOB_ALL_FAILURE";

export const FETCH_JOB_TIMELINE_LIST = "FETCH_JOB_TIMELINE_LIST";
export const FETCH_JOB_TIMELINE_LIST_SUCCESS =
  "FETCH_JOB_TIMELINE_LIST_SUCCESS";
export const FETCH_JOB_TIMELINE_LIST_FAILURE =
  "FETCH_JOB_TIMELINE_LIST_FAILURE";

export const JOB_TIMELINE_COUNT = "JOB_TIMELINE_COUNT";
export const JOB_TIMELINE_COUNT_SUCCESS = "JOB_TIMELINE_COUNT_SUCCESS";
export const JOB_TIMELINE_COUNT_FAILURE = "JOB_TIMELINE_COUNT_FAILURE";

export const TAG_JOB_ATTACHMENT = "TAG_JOB_ATTACHMENT";
export const TAG_JOB_ATTACHMENT_SUCCESS = "TAG_JOB_ATTACHMENT_SUCCESS";
export const TAG_JOB_ATTACHMENT_FAILURE = "TAG_JOB_ATTACHMENT_FAILURE";
export const TAG_JOB_ATTACHMENT_RESET = "TAG_JOB_ATTACHMENT_RESET";
