export const FETCH_COUNTRYCURRENCY = 'FETCH_COUNTRYCURRENCY';
export const FETCH_COUNTRYCURRENCY_SUCCESS = 'FETCH_COUNTRYCURRENCY_SUCCESS';
export const FETCH_COUNTRYCURRENCY_FAILURE = 'FETCH_COUNTRYCURRENCY_FAILURE';

export const FETCH_BUSINESS_COUNTRIES = 'FETCH_BUSINESS_COUNTRIES';
export const FETCH_BUSINESS_COUNTRIES_SUCCESS = 'FETCH_BUSINESS_COUNTRIES_SUCCESS';
export const FETCH_BUSINESS_COUNTRIES_FAILURE = 'FETCH_BUSINESS_COUNTRIES_FAILURE';
