export const FETCH_JOB_LIST = "FETCH_JOB_LIST";
export const FETCH_JOB_LIST_SUCCESS = "FETCH_JOB_LIST_SUCCESS";
export const FETCH_JOB_LIST_FAILURE = "FETCH_JOB_LIST_FAILURE";

export const FETCH_JOB_LISTS = "FETCH_JOB_LISTS";
export const FETCH_JOB_LISTS_SUCCESS = "FETCH_JOB_LISTS_SUCCESS";
export const FETCH_JOB_LISTS_FAILURE = "FETCH_JOB_LISTS_FAILURE";

export const CREATE_JOB_LIST = "CREATE_JOB_LIST";
export const CREATE_JOB_LIST_SUCCESS = "CREATE_JOB_LIST_SUCCESS";
export const CREATE_JOB_LIST_FAILURE = "CREATE_JOB_LIST_FAILURE";

export const POST_JOB_LIST = "POST_JOB_LIST";
export const POST_JOB_LIST_SUCCESS = "POST_JOB_LIST_SUCCESS";
export const POST_JOB_LIST_FAILURE = "POST_JOB_LIST_FAILURE";

export const PUT_JOB_LIST = "PUT_JOB_LIST";
export const PUT_JOB_LIST_SUCCESS = "PUT_JOB_LIST_SUCCESS";
export const PUT_JOB_LIST_FAILURE = "PUT_JOB_LIST_FAILURE";

export const DELETE_JOB_LIST = "DELETE_JOB_LIST";
export const DELETE_JOB_LIST_SUCCESS = "DELETE_JOB_LIST_SUCCESS";
export const DELETE_JOB_LIST_FAILURE = "DELETE_JOB_LIST_FAILURE";

export const FETCH_JOB_LISTS_FIELDS = "FETCH_JOB_LISTS_FIELDS";
export const FETCH_JOB_LISTS_FIELDS_SUCCESS = "FETCH_JOB_LISTS_FIELDS_SUCCESS";
export const FETCH_JOB_LISTS_FIELDS_FAILURE = "FETCH_JOB_LISTS_FIELDS_FAILURE";

export const FETCH_USER_GROUP_BY_NAME = "FETCH_USER_GROUP_BY_NAME";
export const FETCH_USER_GROUP_BY_NAME_SUCCESS =
  "FETCH_USER_GROUP_BY_NAME_SUCCESS";
export const FETCH_USER_GROUP_BY_NAME_FAILURE =
  "FETCH_USER_GROUP_BY_NAME_FAILURE";

export const CREATE_JOB_FOD = "CREATE_JOB_FOD";
export const CREATE_JOB_FOD_SUCCESS = "CREATE_JOB_FOD_SUCCESS";
export const CREATE_JOB_FOD_FAILURE = "CREATE_JOB_FOD_FAILURE";

export const FETCH_JOBS_ADMIN = "FETCH_JOBS_ADMIN";
export const FETCH_JOBS_ADMIN_SUCCESS = "FETCH_JOBS_ADMIN_SUCCESS";
export const FETCH_JOBS_ADMIN_FAILURE = "FETCH_JOBS_ADMIN_FAILURE";

