export const FETCH_ACCOUNTFORM = 'FETCH_ACCOUNTFORM';
export const FETCH_ACCOUNTFORM_SUCCESS = 'FETCH_ACCOUNTFORM_SUCCESS';
export const FETCH_ACCOUNTFORM_FAILURE = 'FETCH_ACCOUNTFORM_FAILURE';

export const FETCH_ACCOUNTFORM_SUBMISSION = 'FETCH_ACCOUNTFORM_SUBMISSION';
export const FETCH_ACCOUNTFORM_SUBMISSION_SUCCESS = 'FETCH_ACCOUNTFORM_SUBMISSION_SUCCESS';
export const FETCH_ACCOUNTFORM_SUBMISSION_FAILURE = 'FETCH_ACCOUNTFORM_SUBMISSION_FAILURE';

export const CLEAR_ACCOUNTFORM_SUBMISSION = 'CLEAR_ACCOUNTFORM_SUBMISSION';

export const SET_FORM_SUBMISSION = 'SET_FORM_SUBMISSION';






