export const FETCH_CANDIDATE = "FETCH_CANDIDATE";
export const FETCH_CANDIDATE_SUCCESS = "FETCH_CANDIDATE_SUCCESS";
export const FETCH_CANDIDATE_FAILURE = "FETCH_CANDIDATE_FAILURE";

export const FETCH_CANDIDATES = "FETCH_CANDIDATES";
export const FETCH_CANDIDATES_SUCCESS = "FETCH_CANDIDATES_SUCCESS";
export const FETCH_CANDIDATES_FAILURE = "FETCH_CANDIDATES_FAILURE";

export const CREATE_CANDIDATE = "CREATE_CANDIDATE";
export const CREATE_CANDIDATE_SUCCESS = "CREATE_CANDIDATE_SUCCESS";
export const CREATE_CANDIDATE_FAILURE = "CREATE_CANDIDATE_FAILURE";

export const POST_CANDIDATE = "POST_CANDIDATE";
export const POST_CANDIDATE_SUCCESS = "POST_CANDIDATE_SUCCESS";
export const POST_CANDIDATE_FAILURE = "POST_CANDIDATE_FAILURE";

export const PUT_CANDIDATE = "PUT_CANDIDATE";
export const PUT_CANDIDATE_SUCCESS = "PUT_CANDIDATE_SUCCESS";
export const PUT_CANDIDATE_FAILURE = "PUT_CANDIDATE_FAILURE";

export const DELETE_CANDIDATE = "DELETE_CANDIDATE";
export const DELETE_CANDIDATE_SUCCESS = "DELETE_CANDIDATE_SUCCESS";
export const DELETE_CANDIDATE_FAILURE = "DELETE_CANDIDATE_FAILURE";

export const FETCH_CANDIDATES_FIELDS = "FETCH_CANDIDATES_FIELDS";
export const FETCH_CANDIDATES_FIELDS_SUCCESS = "FETCH_CANDIDATES_FIELDS_SUCCESS";
export const FETCH_CANDIDATES_FIELDS_FAILURE = "FETCH_CANDIDATES_FIELDS_FAILURE";

export const RESET_META_DATA = "RESET_META_DATA";

export const PUT_CANDIDATE_DRAFT_STATUS = "PUT_CANDIDATE_DRAFT_STATUS";
export const PUT_CANDIDATE_DRAFT_STATUS_SUCCESS = "PUT_CANDIDATE_DRAFT_STATUS_SUCCESS";
export const PUT_CANDIDATE_DRAFT_STATUS_FAILURE = "PUT_CANDIDATE_DRAFT_STATUS_FAILURE";
