// CREATE JOB CUSTOM VIEW
export const CREATE_JOB_CUSTOM_VIEW = "CREATE_JOB_CUSTOM_VIEW";
export const CREATE_JOB_CUSTOM_VIEW_SUCCESS = "CREATE_JOB_CUSTOM_VIEW_SUCCESS";
export const CREATE_JOB_CUSTOM_VIEW_FAILURE = "CREATE_JOB_CUSTOM_VIEW_FAILURE";

// FETCH JOB CUSTOM VIEW
export const FETCH_JOB_CUSTOM_VIEW = "FETCH_JOB_CUSTOM_VIEW";
export const FETCH_JOB_CUSTOM_VIEW_SUCCESS = "FETCH_JOB_CUSTOM_VIEW_SUCCESS";
export const FETCH_JOB_CUSTOM_VIEW_FAILURE = "FETCH_JOB_CUSTOM_VIEW_FAILURE";
