// CREATE CANDIDATE CUSTOM VIEW
export const CREATE_CANDIDATE_CUSTOM_VIEW = "CREATE_CANDIDATE_CUSTOM_VIEW";
export const CREATE_CANDIDATE_CUSTOM_VIEW_SUCCESS = "CREATE_CANDIDATE_CUSTOM_VIEW_SUCCESS";
export const CREATE_CANDIDATE_CUSTOM_VIEW_FAILURE = "CREATE_CANDIDATE_CUSTOM_VIEW_FAILURE";

// FETCH CANDIDATE CUSTOM VIEW
export const FETCH_CANDIDATE_CUSTOM_VIEW = "FETCH_CANDIDATE_CUSTOM_VIEW";
export const FETCH_CANDIDATE_CUSTOM_VIEW_SUCCESS = "FETCH_CANDIDATE_CUSTOM_VIEW_SUCCESS";
export const FETCH_CANDIDATE_CUSTOM_VIEW_FAILURE = "FETCH_CANDIDATE_CUSTOM_VIEW_FAILURE";