export const ACCOUNT = "accounts"
export const GEO = "geo"
export const INDUSTRY = "industries"
export const DEPARTMENT = "departments"
export const USERGROUP = "api/usergroup"
export const DOCUMENTS = "documents"